spring.application.name=outpass-service

server.port=8081

spring.datasource.url=jdbc:postgresql://ep-dawn-rice-ayo1fj1f.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BWPp2ol3gYDy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone = https://service-registry-1u9p.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka - Confluent Cloud
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_API_KEY}" password="${KAFKA_API_SECRET}";

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

jwt.secret = p|}yR?-#mON21{-V<fxj$R//]?j0>.wkeoD(B#OG$(R
security.qr-secret=6hKvPsRSc+e7Ehkvt44ahqkU5f9ntYfAs2XdTU8d+QE=

# Logging
logging.file.name=logs/outpass-service.log

# Log levels
logging.level.root=INFO
logging.level.com.outpass.outpass_service=DEBUG

# Rolling policy
logging.logback.rollingpolicy.file-name-pattern=logs/outpass-service.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.clean-history-on-start=false