spring.application.name=notification-service

server.port = 8003
spring.datasource.url= jdbc:oracle:thin:@localhost:1521:XE

#spring.datasource.url=jdbc:mysql://mysql:3306/outpass_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=system
spring.datasource.password=Admin#123
#spring.datasource.password= root
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.OracleDialect


# Kafka Server
spring.kafka.bootstrap-servers=localhost:9092

# Consumer Group
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.application.notification_service.dto.OutpassEvent
# Allow JSON conversion
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#Email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kalyandesineedi@gmail.com
spring.mail.password=eptdacneqkyoboqc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details= always

eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true

eureka.instance.hostname=localhost
