spring.application.name=notification-service

server.port = 8003


spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092

# Consumer Group
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${JBTHGLG46PZYUVN3}" password="${cflta2DUjGFlTace8ThISk8mR8BWrIFF+qPyXrz6A7wOXYbpm7EC6o41ftPkjGhw}";
# Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.application.notification_service.dto.OutpassEvent
# Allow JSON conversion
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#Email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kalyandesineedi@gmail.com
spring.mail.password=eptdacneqkyoboqc

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

eureka.client.service-url.defaultZone = https://service-registry-1u9p.onrender.com/eureka
eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true


