spring.application.name=auth-service
server.port=8082

eureka.client.service-url.defaultZone = https://service-registry-1u9p.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry= true
eureka.instance.prefer-ip-address= true

#spring.datasource.url=jdbc:postgresql://ep-dawn-rice-ayo1fj1f.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_BWPp2ol3gYDy
spring.datasource.url=${jdbc:postgresql://ep-dawn-rice-ayo1fj1f.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${neondb_owner}
spring.datasource.password=${npg_BWPp2ol3gYDy}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=always

#server.forward-headers-strategy=framework
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
#
#springdoc.swagger-ui.url=/auth-service/v3/api-docs
#springdoc.swagger-ui.config-url=/auth-service/v3/api-docs/swagger-config

#springdoc.swagger-ui.disable-swagger-default-url=true
jwt.secret = p|}yR?-#mON21{-V<fxj$R//]?j0>.wkeoD(B#OG$(R
jwt.expiration = 3600000


# Admin bootstrap
admin.user-id=${ADMIN_USER_ID:USRADMIN001}
admin.email=${ADMIN_EMAIL:admin@outpass.com}
admin.password=${ADMIN_PASSWORD:Admin@123}
admin.first-name=${ADMIN_FIRST_NAME:System}
admin.last-name=${ADMIN_LAST_NAME:Administrator}



logging.level.com.outpass.auth_service=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=DEBUG
logging.level.org.hibernate.SQL=DEBUG

logging.file.name=logs/auth-service.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB