spring.application.name=auth-service
server.port= 8082

eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry= true
eureka.instance.prefer-ip-address= true

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url= jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=Admin#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.OracleDialect

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.springframwork.security = INFO
logging.level.org.hibernate.SQL = debug

jwt.secret = p|}yR?-#mON21{-V<fxj$R//]?j0>.wkeoD(B#OG$(R
jwt.expiration = 3600000
