spring.application.name=profile-service

server.port=8083

spring.datasource.url=jdbc:postgresql://ep-dawn-rice-ayo1fj1f.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BWPp2ol3gYDy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone = https://service-registry-1u9p.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.secret = p|}yR?-#mON21{-V<fxj$R//]?j0>.wkeoD(B#OG$(R

services.auth.url=https://auth-service-gktb.onrender.com

# ============================================================
# LOG LEVELS
# ============================================================

# Your application
logging.level.com.outpass.profile_service=INFO

# Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=DEBUG

# Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG

# Hibernate bind parameters - enable only when debugging SQL
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Feign clients - only if profile-service calls other services
logging.level.com.outpass.profile_service.client=DEBUG

# Kafka - only if profile-service uses Kafka
logging.level.org.springframework.kafka=INFO


# ============================================================
# LOG FILE STORAGE
# ============================================================

logging.file.name=logs/profile-service.log

# ============================================================
# LOG ROTATION
# ============================================================

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB