spring.application.name=profile-service

server.port=8083

# Database
# spring.datasource.url=jdbc:mysql://localhost:3306/outpass_db
# spring.datasource.url=jdbc:mysql://mysql:3306/outpass_db?allowPublicKeyRetrieval=true&useSSL=false
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url= jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=Admin#123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.OracleDialect

## Kafka
#spring.kafka.bootstrap-servers=localhost:9092
#
## Consumer
#spring.kafka.consumer.group-id=notification-group
#spring.kafka.consumer.auto-offset-reset=earliest
#
## Producer
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.properties.spring.json.add.type.headers=false
#
## Actuator
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=always

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.secret = p|}yR?-#mON21{-V<fxj$R//]?j0>.wkeoD(B#OG$(R

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/profile-service/v3/api-docs
springdoc.swagger-ui.config-url=/profile-service/v3/api-docs/swagger-config
springdoc.swagger-ui.disable-swagger-default-url=true

# ============================================================
# LOG LEVELS
# ============================================================

# Your application
logging.level.com.outpass.profile_service=INFO

# Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=DEBUG

# Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG

# Hibernate bind parameters - enable only when debugging SQL
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Feign clients - only if profile-service calls other services
logging.level.com.outpass.profile_service.client=DEBUG

# Kafka - only if profile-service uses Kafka
logging.level.org.springframework.kafka=INFO


# ============================================================
# LOG FILE STORAGE
# ============================================================

logging.file.name=logs/profile-service.log

# ============================================================
# LOG ROTATION
# ============================================================

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB