spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "https://front-end-outpass-management-system.vercel.app/"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          routes:

            - id: auth-service
              uri: https://auth-service-gktb.onrender.com
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1

            - id: profile-service
              uri: https://backend-outpass-management-system.onrender.com
              predicates:
                - Path=/profile-service/**
              filters:
                - StripPrefix=1

            - id: outpass-service
              uri: https://outpass-service.onrender.com
              predicates:
                - Path=/outpass-service/**
              filters:
                - StripPrefix=1

            - id: notification-service
              uri: https://notification-service-sm87.onrender.com
              predicates:
                - Path=/notification-service/**
              filters:
                - StripPrefix=1

      x-forwarded:
        enabled: true
        for-enabled: true
        host-enabled: true
        port-enabled: true
        proto-enabled: true
        prefix-enabled: true