spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id= true
spring.cloud.gateway.server.webflux.discovery.locator.enabled= true


#Health checking
management.endpoints.web.exposure.include = health,info,gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


#jwt validation
jwt.secret = p|}yR?-#mON21{-V<fxj$R//]?j0>.wkeoD(B#OG$(R
