spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:

          # CORS
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

          # Routes
          routes:

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1

            - id: outpass-service
              uri: lb://outpass-service
              predicates:
                - Path=/outpass-service/**
              filters:
                - StripPrefix=1

          # Forwarded headers
          x-forwarded:
            enabled: true
            for-enabled: true
            host-enabled: true
            port-enabled: true
            proto-enabled: true
            prefix-enabled: true